[ { place: 'Wageningen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Wageningen', year: 2000, subject: 'Haak, Johan' } ] },
  { place: 'Alphen aan den Rijn',
    longitude:  5.66306,
    latitude: 51.96444,
    bookCount: 1,
    books:
     [ { place: 'Alphen aan den Rijn',
         year: 1976,
         subject: 'Hollander, Arie Nicolaas Jan den (1906-1976)' } ] },
  { place: 'Haarlem',
    longitude: undefined,
    latitude: undefined,
    bookCount: 5,
    books:
     [ { place: 'Haarlem', year: 1995, subject: 'vriendschap' },
       { place: 'Haarlem', year: 1986, subject: 'Puchinger, G' },
       { place: 'Haarlem', year: 1995, subject: 'eenzaamheid' },
       { place: 'Haarlem', year: 2002, subject: 'Noord-Holland' },
       { place: 'Haarlem', year: 2002, subject: 'Zenboeddhisme' } ] },
  { place: 'Amsterdam',
    longitude: undefined,
    latitude: undefined,
    bookCount: 48,
    books:
     [ { place: 'Amsterdam', year: 2004, subject: 'Wereldoorlog I' },
       { place: 'Amsterdam',
         year: 1995,
         subject: 'Monumenten; IJ-oevers (Amsterdam)' },
       { place: 'Amsterdam',
         year: 1995,
         subject: 'Stichting van de Arbeid' },
       { place: 'Amsterdam',
         year: 1987,
         subject: 'Cultuurfilosofie; Opstellen' },
       { place: 'Amsterdam',
         year: 1999,
         subject: 'Diet Kloos-Barendrecht 1924-' },
       { place: 'Amsterdam', year: 1993, subject: 'Keesing' },
       { place: 'Amsterdam', year: 2001, subject: 'Middenstand' },
       { place: 'Amsterdam', year: 2001, subject: 'Discriminatie' },
       { place: 'Amsterdam', year: 2005, subject: 'Vrouwen' },
       { place: 'Amsterdam',
         year: 1999,
         subject: 'Woningbouwprojecten' },
       { place: 'Amsterdam', year: 2005, subject: 'Wereldbibliotheek' },
       { place: 'Amsterdam', year: 1985, subject: 'Verzuiling' },
       { place: 'Amsterdam', year: 1970, subject: 'Gogh, Vincent van' },
       { place: 'Amsterdam', year: 1997, subject: 'Homoseksualiteit' },
       { place: 'Amsterdam', year: 2002, subject: 'Popmuziek' },
       { place: 'Amsterdam',
         year: 2005,
         subject: 'Wetenschappelijk onderwijs' },
       { place: 'Amsterdam',
         year: 1997,
         subject: 'Ferdinand Domela Nieuwenhuis 1846-1919' },
       { place: 'Amsterdam', year: 2001, subject: 'Vloeken' },
       { place: 'Amsterdam', year: 1990, subject: 'zigeuners' },
       { place: 'Amsterdam',
         year: 2001,
         subject: 'Nederlands Oost-Indië' },
       { place: 'Amsterdam', year: 1999, subject: 'Allochtonen' },
       { place: 'Amsterdam',
         year: 1995,
         subject: 'Jan Marius Romein 1893-1962' },
       { place: 'Amsterdam', year: 2004, subject: 'Jodenvervolging' },
       { place: 'Amsterdam', year: 1995, subject: 'Amsterdam' },
       { place: 'Amsterdam',
         year: 2001,
         subject: 'Rechten van de mens' },
       { place: 'Amsterdam',
         year: 1989,
         subject: 'Wilhelminagasthuis (Amsterdam)' },
       { place: 'Amsterdam', year: 2000, subject: 'Biografieën' },
       { place: 'Amsterdam', year: 1990, subject: 'Daum, P.A' },
       { place: 'Amsterdam',
         year: 2001,
         subject: "Alex d'Electrique (toneelgroep)" },
       { place: 'Amsterdam', year: 1987, subject: 'Kabafes, K.P' },
       { place: 'Amsterdam', year: 1994, subject: 'Biografieën' },
       { place: 'Amsterdam',
         year: 1994,
         subject: 'Buitenlandse kinderen' },
       { place: 'Amsterdam', year: 1987, subject: 'Mechanicus, Philip' },
       { place: 'Amsterdam', year: 1987, subject: 'Nijhoff, M' },
       { place: 'Amsterdam', year: 1992, subject: 'Grafmonumenten' },
       { place: 'Amsterdam', year: 2003, subject: 'Vestdijk, S' },
       { place: 'Amsterdam', year: 1995, subject: 'Duitse emigranten' },
       { place: 'Amsterdam', year: 1992, subject: 'Modejournalistiek' },
       { place: 'Amsterdam',
         year: 1998,
         subject: 'Halberstam, Adele 1871-1943' },
       { place: 'Amsterdam', year: 1989, subject: 'Opstellen' },
       { place: 'Amsterdam',
         year: 1991,
         subject: "Vliegent Hart, 't (Oost-Indiëvaarder)" },
       { place: 'Amsterdam', year: 1997, subject: 'Zeerecht' },
       { place: 'Amsterdam', year: 1992, subject: 'Tlacayelel' },
       { place: 'Amsterdam', year: 1988, subject: 'Democratie' },
       { place: 'Amsterdam', year: 1991, subject: 'Feminisme' },
       { place: 'Amsterdam', year: 1999, subject: 'Uganda' },
       { place: 'Amsterdam', year: 2001, subject: 'Kohnstamm, Ph' },
       { place: 'Amsterdam',
         year: 1990,
         subject: 'Charrière, Isabelle de' } ] },
  { place: 'Eindhoven',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Eindhoven', year: 1993, subject: 'Heiligen' } ] },
  { place: 'Rijswijk',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Rijswijk',
         year: 1991,
         subject: 'Luchtmacht Stafschool (Rijswijk)' } ] },
  { place: 'Arnhem',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Arnhem', year: 1999, subject: 'Zilversmeedkunst' } ] },
  { place: 'Averbode',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Averbode', year: 1994, subject: 'Mystiek' } ] },
  { place: 'Abcoude',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Abcoude',
         year: 2002,
         subject: 'Illegale buitenlanders' } ] },
  { place: 'Baarn',
    longitude: undefined,
    latitude: undefined,
    bookCount: 6,
    books:
     [ { place: 'Baarn', year: 1995, subject: 'Dood' },
       { place: 'Baarn', year: 1995, subject: 'Geheugentraining' },
       { place: 'Baarn', year: 1995, subject: 'Geheugentraining' },
       { place: 'Baarn', year: 1998, subject: 'Angelus Silesius' },
       { place: 'Baarn', year: 1987, subject: 'Brieven' },
       { place: 'Baarn', year: 1995, subject: 'Geboortekaartjes' } ] },
  { place: 'Den Haag',
    longitude: undefined,
    latitude: undefined,
    bookCount: 10,
    books:
     [ { place: 'Den Haag', year: 1995, subject: 'Taalgebruik' },
       { place: 'Den Haag',
         year: 1997,
         subject: 'Cornelis Anthony Jacobus van Dishoeck 1863-1931' },
       { place: 'Den Haag', year: 1996, subject: 'Besluitvorming' },
       { place: 'Den Haag', year: 1999, subject: 'Hoornik, Eduard' },
       { place: 'Den Haag',
         year: 2000,
         subject: "Nassaukwartier ('s-Gravenhage)" },
       { place: 'Den Haag',
         year: 2000,
         subject: 'Hillegonda van Uildriks 1863-1921' },
       { place: 'Den Haag', year: 2005, subject: 'Meidagen (1940)' },
       { place: 'Den Haag', year: 1991, subject: 'Leesgewoonten' },
       { place: 'Den Haag', year: 1997, subject: 'Nederland' },
       { place: 'Den Haag', year: 2001, subject: '18e eeuw' } ] },
  { place: 'Utrecht',
    longitude: undefined,
    latitude: undefined,
    bookCount: 10,
    books:
     [ { place: 'Utrecht', year: 1994, subject: 'Nederlandse taal' },
       { place: 'Utrecht', year: 1997, subject: 'Moesman, J.H' },
       { place: 'Utrecht', year: 2002, subject: 'Zelfverwerkelijking' },
       { place: 'Utrecht', year: 1993, subject: 'Vrouwen' },
       { place: 'Utrecht', year: 1990, subject: 'Castella scheerzeep' },
       { place: 'Utrecht',
         year: 2003,
         subject: 'Russische leenwoorden' },
       { place: 'Utrecht', year: 2003, subject: 'Toespraken' },
       { place: 'Utrecht', year: 1998, subject: 'Toespraken' },
       { place: 'Utrecht',
         year: 2002,
         subject: 'Nederlands Instituut voor Kerkmuziek' },
       { place: 'Utrecht', year: 1994, subject: 'Slavernij' } ] },
  { place: 'Leuven',
    longitude: undefined,
    latitude: undefined,
    bookCount: 3,
    books:
     [ { place: 'Leuven', year: 1989, subject: 'Vlaamse poëzie' },
       { place: 'Leuven', year: 2002, subject: 'Guldensporenslag' },
       { place: 'Leuven', year: 2000, subject: 'Straathandel' } ] },
  { place: 'Leuven ; Apeldoorn',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Leuven ; Apeldoorn',
         year: 1993,
         subject: 'Poëzie ; opstellen' } ] },
  { place: 'Heerhugowaard',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Heerhugowaard', year: 2004, subject: 'Biecht' } ] },
  { place: 'Maastricht',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Maastricht', year: 1992, subject: 'Dijk, J.L.M. van' } ] },
  { place: 'London',
    longitude: undefined,
    latitude: undefined,
    bookCount: 3,
    books:
     [ { place: 'London',
         year: 1977,
         subject: 'Fuller, John Frederick Charles' },
       { place: 'London', year: 1994, subject: 'Interieurkunst' },
       { place: 'London', year: 1999, subject: 'Monarchie' } ] },
  { place: 'Weert',
    longitude: undefined,
    latitude: undefined,
    bookCount: 3,
    books:
     [ { place: 'Weert', year: 1993, subject: 'Toneelwereld' },
       { place: 'Weert', year: 1988, subject: 'Nederland' },
       { place: 'Weert', year: 2001, subject: 'Honden' } ] },
  { place: 'Enschede',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Enschede', year: 1998, subject: 'Korenmolens' } ] },
  { place: 'Rotterdam',
    longitude: undefined,
    latitude: undefined,
    bookCount: 4,
    books:
     [ { place: 'Rotterdam', year: 1998, subject: 'Glaskunst' },
       { place: 'Rotterdam',
         year: 2002,
         subject: 'Grafische vormgeving' },
       { place: 'Rotterdam', year: 1994, subject: 'Economen' },
       { place: 'Rotterdam',
         year: 1992,
         subject: 'Prina, Stephen; Tentoonstellingscatalogi' } ] },
  { place: 'Rennes',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Rennes', year: 1998, subject: 'Computerkunst' } ] },
  { place: 'Delft',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Delft', year: 1987, subject: 'Ketel, Cornelis' } ] },
  { place: 'Nederhorst den Berg',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Nederhorst den Berg',
         year: 1990,
         subject: 'Uitkeringsgerechtigden' } ] },
  { place: 'Hilversum',
    longitude: undefined,
    latitude: undefined,
    bookCount: 8,
    books:
     [ { place: 'Hilversum',
         year: 2005,
         subject: 'Joodse oorlogspleegkinderen' },
       { place: 'Hilversum',
         year: 2000,
         subject: 'Jan Carel Josephus van Speyk 1802-1831' },
       { place: 'Hilversum',
         year: 2000,
         subject: 'Hendrikus Colijn 1869-1944' },
       { place: 'Hilversum', year: 2002, subject: '18e eeuw' },
       { place: 'Hilversum', year: 2001, subject: '19e eeuw' },
       { place: 'Hilversum', year: 1990, subject: 'Suriname' },
       { place: 'Hilversum', year: 1990, subject: 'Geloofsbeleving' },
       { place: 'Hilversum', year: 2001, subject: 'Dagboeken' } ] },
  { place: 's-Gravenhage',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 's-Gravenhage', year: 1997, subject: "'s-Gravenhage" } ] },
  { place: 'Kampen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 5,
    books:
     [ { place: 'Kampen', year: 1991, subject: 'Industriepastoraat' },
       { place: 'Kampen',
         year: 1995,
         subject: 'Amerikaanse schrijvers' },
       { place: 'Kampen', year: 1996, subject: 'Jodendom' },
       { place: 'Kampen', year: 1996, subject: 'CDA' },
       { place: 'Kampen', year: 1991, subject: 'Kierkegaard, Soren' } ] },
  { place: 'Vlissingen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Vlissingen', year: 2000, subject: 'Wandeltochten' } ] },
  { place: 'Weesp',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Weesp', year: 1984, subject: 'Platbodemschepen' } ] },
  { place: 'Bergen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Bergen',
         year: 1993,
         subject: 'Nederlandse schrijvers' } ] },
  { place: 'Cambridge',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Cambridge',
         year: 1982,
         subject: 'Berlioz, Harriet Smithson' } ] },
  { place: 'Nijmegen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 2,
    books:
     [ { place: 'Nijmegen',
         year: 2002,
         subject: 'Feyenoord (voetbalclub)' },
       { place: 'Nijmegen', year: 1995, subject: 'Vlaamse Primitieven' } ] },
  { place: "'s-Gravenhage",
    longitude: undefined,
    latitude: undefined,
    bookCount: 6,
    books:
     [ { place: "'s-Gravenhage", year: 1986, subject: 'Werkloosheid' },
       { place: "'s-Gravenhage",
         year: 1988,
         subject: 'Fabriekswoningen' },
       { place: "'s-Gravenhage", year: 1992, subject: 'Greshoff' },
       { place: "'s-Gravenhage", year: 1995, subject: 'Collaboratie' },
       { place: "'s-Gravenhage", year: 2004, subject: 'Taalgebruik' },
       { place: "'s-Gravenhage", year: 1997, subject: 'Feministen' } ] },
  { place: 'Groningen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Groningen', year: 2000, subject: 'Meertalige boeken' } ] },
  { place: 'Waasmunster',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Waasmunster', year: 2003, subject: 'Kruistochten' } ] },
  { place: 'Zwolle',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Zwolle',
         year: 1995,
         subject: 'Regnault, Pierre Alexandre' } ] },
  { place: 'Oldenzaal',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Oldenzaal', year: 1995, subject: 'Biografieën' } ] },
  { place: 'Houten',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Houten', year: 2000, subject: 'Voetbal' } ] },
  { place: 'Tielt',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Tielt', year: 2003, subject: 'Meditaties (R.K.)' } ] },
  { place: 'Hasselt',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Hasselt', year: 2004, subject: 'Herfst' } ] },
  { place: 'Leeuwarden',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Leeuwarden', year: 1999, subject: 'Begraafplaatsen' } ] },
  { place: 'Assen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Assen', year: 2005, subject: '17e eeuw' } ] },
  { place: 'Warmond',
    longitude: undefined,
    latitude: undefined,
    bookCount: 2,
    books:
     [ { place: 'Warmond', year: 1991, subject: 'Verzet' },
       { place: 'Warmond', year: 1999, subject: 'Verzet' } ] },
  { place: 'Zutphen',
    longitude: undefined,
    latitude: undefined,
    bookCount: 4,
    books:
     [ { place: 'Zutphen',
         year: 2004,
         subject: 'Antoinette Bourignon 1616-1680' },
       { place: 'Zutphen',
         year: 2005,
         subject: 'S.W.A. van Voerst van Lynden' },
       { place: 'Zutphen', year: 1995, subject: 'Literatuuronderwijs' },
       { place: 'Zutphen', year: 1995, subject: 'Literatuuronderwijs' } ] },
  { place: 'Nijkerk',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Nijkerk', year: 1995, subject: 'Wilhelmus' } ] },
  { place: 'Vught',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Vught', year: 1991, subject: 'Nederlandse dichters' } ] },
  { place: 'Dordrecht',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Dordrecht',
         year: 1999,
         subject: 'Openbare Bibliotheek Dordrecht' } ] },
  { place: 'Sliedrecht',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Sliedrecht', year: 1998, subject: 'Meertalige boeken' } ] },
  { place: "'s-Hertogenbosch",
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: "'s-Hertogenbosch",
         year: 1931,
         subject: 'Metamorfoze Collectie Oude Kinderboeken' } ] },
  { place: 'Tiel',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Tiel', year: 1998, subject: 'Spiritisme' } ] },
  { place: 'Atlantic Highlands, N.J.',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Atlantic Highlands, N.J.',
         year: 1985,
         subject: 'Shakespeare, William' } ] },
  { place: 'Breda',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books: [ { place: 'Breda', year: 2001, subject: 'Katten' } ] },
  { place: 'Voorburg',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Voorburg', year: 1998, subject: 'Pueblo (volk)' } ] },
  { place: 'Tilburg',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Tilburg', year: 1993, subject: 'Boon, Louis Paul' } ] },
  { place: 'Ljouwert/Leeuwarden',
    longitude: undefined,
    latitude: undefined,
    bookCount: 1,
    books:
     [ { place: 'Ljouwert/Leeuwarden',
         year: 1993,
         subject: 'Friese taal; Geschiedenis' } ] } ]
